llm:
  provider: huggingface
  config:
    model: 'mistralai/Mistral-7B-Instruct-v0.2'
    temperature: 0.5
    max_tokens: 1000
    top_p: 0.5
    stream: false

vectordb:
  provider: chroma
  config:
    collection_name: 'my-collection'
    dir: db
    allow_reset: true

embedder:
  provider: huggingface
  config:
    model: 'sentence-transformers/all-mpnet-base-v2'